// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "1 - (TR) - Temel Bilgiler",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "1 - (TR) - Temel Bilgiler",
            targets: ["AppModule"],
            bundleIdentifier: "NomoSiOS.Constant--Variables-and-Data-Types-TR",
            teamIdentifier: "MW2482B7WH",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cat),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)